#This file contains setting used in the data processing

osm_fp: '../data/raw/osm/kbhaug22.osm.pbf' # '../data/osm/custom_files/denmark-latest.osm.pbf' 
geodk_fp: '../data/raw/geodk/VEJMIDTE_BRUDT.shp'
geodk_id_col: 'fot_id'
pop_fp_1: '../data/raw/pop/GHS_POP_E2020_GLOBE_R2022A_54009_100_V1_0_R3_C19/GHS_POP_E2020_GLOBE_R2022A_54009_100_V1_0_R3_C19.tif'
pop_fp_2: '../data/raw/pop/GHS_POP_E2020_GLOBE_R2022A_54009_100_V1_0_R3_C20/GHS_POP_E2020_GLOBE_R2022A_54009_100_V1_0_R3_C20.tif'
settlement_fp_1:
settlement_fp_2: 

CRS: 'EPSG:25832'

db_name: 'bike_network'
db_user: 'postgres'
db_port: '5432'
db_host: 'localhost'
db_password: 'aneitu'

study_area: 'DK'

muni_fp: '../data/muni_boundary.gpkg'

