#This file contains setting used in the data processing

study_area: 'testarea'
osm_fp: '../data/planet_kbh.osm.pbf'
geodk_fp: '../data/vejmidte_brudt_subset.gpkg'
muni_fp: '../data/muni_boundary.gpkg'
grid_fp: '../data/DKgrid_SHP_UTM32-ETRS89/DKN_1km_euref89.shp'
CRS: 'EPSG:25832'

db_name: 'bike_network'
db_user: 'postgres'
db_port: '5432'
db_host: 'localhost'
db_password: 'aneitu'