#This file contains setting used in the data processing

use_postgres: True

osm_fp: '../data/osm/custom_files/denmark-latest.osm.pbf' #'../data/raw/planet_kbh.osm.pbf'
geodk_fp: '../data/geodk/vejmidte_brudt.gpkg'
geodk_id_col: 'fot_id'

CRS: 'EPSG:25832'

db_name: 'bike_network'
db_user: 'postgres'
db_port: '5432'
db_host: 'localhost'
db_password: 'aneitu'


study_area: 'DK'

muni_fp: '../data/muni_boundary.gpkg'
grid_fp: '../data/DKgrid_SHP_UTM32-ETRS89/DKN_1km_euref89.shp'


quality_check: True
quality_data: '../data/.json' # Data to be used for quality metrics for data matching

