#This file contains setting used in the data processing

study_area: 'testarea'
OSM_fp: '../data/planet_11.3481,55.5705_11.8357,55.7403.osm.pbf'
CRS: 'EPSG:25832'

db_name: 'bike_network'
db_user: 'postgres'
db_port: '5432'
db_host: 'localhost'
